// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package recode

import (
	"database/sql"
)

type Pref struct {
	ID      int64
	Rootdir sql.NullString
}

type Recode struct {
	ID        int64
	Origin    string
	Dest      string
	Season    string
	Episode   string
	Processed bool
	Createdat int64
	Updatedat int64
}
